# Entfernenn Sie das '#' in der nächsten Zeile, um Compileroptimierungen
# einzuschalten.
#OPT = -O

all: integrate

integrate: integrate.cpp
	mpic++ $(OPT) -o integrate integrate.cpp

clean:
	rm -f *.o *.c~ integrate
 

