# Entfernenn Sie das '#' in der nächsten Zeile, um Compileroptimierungen
# einzuschalten.
#OPT = -O

all: point2point

point2point: point2point.cpp
	mpic++ $(OPT) -o point2point point2point.cpp

clean:
	rm -f *.o point2point
 
